CREATE TABLE IF NOT EXISTS Artists (
  ID INTEGER PRIMARY KEY,
  Name TEXT NOT NULL
);


CREATE TABLE IF NOT EXISTS Albums (
  ID INTEGER PRIMARY KEY,
  Title TEXT NOT NULL,
  ReleaseDate DATE,
  ArtistID INTEGER,
  FOREIGN KEY (ArtistID) REFERENCES Artists(ID)
);


CREATE TABLE IF NOT EXISTS Tracks (
  ID INTEGER PRIMARY KEY,
  Title TEXT NOT NULL,
  AlbumID INTEGER,
  ArtistID INTEGER,
  Duration INTEGER,
  FOREIGN KEY (AlbumID) REFERENCES Albums(ID),
  FOREIGN KEY (ArtistID) REFERENCES Artists(ID)
);


CREATE TABLE IF NOT EXISTS Users (
  ID INTEGER PRIMARY KEY,
  Username TEXT NOT NULL,
  Password TEXT NOT NULL,
  Email TEXT NOT NULL
);


CREATE TABLE IF NOT EXISTS Playlists (
  ID INTEGER PRIMARY KEY,
  Name TEXT NOT NULL,
  UserID INTEGER,
  FOREIGN KEY (UserID) REFERENCES Users(ID)
);


CREATE TABLE IF NOT EXISTS PlaylistTracks (
  PlaylistID INTEGER,
  TrackID INTEGER,
  PRIMARY KEY (PlaylistID, TrackID),
  FOREIGN KEY (PlaylistID) REFERENCES Playlists(ID),
  FOREIGN KEY (TrackID) REFERENCES Tracks(ID)
);


CREATE TABLE IF NOT EXISTS Favourites (
  UserID INTEGER,
  TrackID INTEGER,
  AlbumID INTEGER,
  PRIMARY KEY (UserID, TrackID),
  FOREIGN KEY (UserID) REFERENCES Users(ID),
  FOREIGN KEY (TrackID) REFERENCES Tracks(ID),
  FOREIGN KEY (AlbumID) REFERENCES Albums(ID)
);
